language: node_js
node_js: node
cache:
  directories:
    - node_modules
script:
  - npm test
env:
  - REACT_APP_API_BASE_URL=https://polar-lake-31524.herokuapp.com/api

before_install:
  - npm install -g npm@5.2.0

before_deploy:
  - npm install netlify-cli -g
  - npm run build

deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p ./build
  skip_cleanup: true
  on:
    branch: react_bootstrap
