language: node_js
node_js: node
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn test
env:
  - REACT_APP_API_BASE_URL=https://polar-lake-31524.herokuapp.com/api

before_install:
  - npm install -g yarn

before_deploy:
  - yarn install netlify-cli -g
  - yarn run build

install:
  - yarn

deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p ./build
  skip_cleanup: true
  on:
    branch: master
