language: node_js
node_js: "lts/*"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn test
env:
  - REACT_APP_API_BASE_URL=https://polar-lake-31524.herokuapp.com/api

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
  - export PATH=$HOME/.yarn/bin:$PATH

before_deploy:
  - yarn global add netlify-cli
  - yarn run build

deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p ./build
  skip_cleanup: true
  on:
    branch: master
